import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Providers } from "@/components/providers"
import { Toast } from "@/components/ui/toast"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: {
    default: "Coins Control",
    template: "%s | Coins Control",
  },
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="relative min-h-dvh bg-background text-fg overflow-hidden">
          {/* Fondo sobrio */}
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute -top-24 -left-24 size-90 rounded-3xl bg-primary/10 blur-3xl" />
            <div className="absolute -bottom-28 -right-28 size-105 rounded-3xl bg-primary/10 blur-3xl" />
            <div className="absolute inset-0 bg-[linear-gradient(to_right,color-mix(in_oklab,var(--color-primary)_10%,transparent)_1px,transparent_1px),linear-gradient(to_bottom,color-mix(in_oklab,var(--color-primary)_10%,transparent)_1px,transparent_1px)] bg-size-[72px_72px] opacity-30" />
          </div>

          <div className="relative">
            <Providers>
              <Toast />
              {children}
            </Providers>
          </div>
        </div>
      </body>
    </html>
  )
}
